# Auto-generated by tools/gen_dockerfiles.py — build the local backend images. Needs Docker Buildx + an NVIDIA GPU host (--build-context and the RUN <<EOT heredocs require buildx). Paths default to this checkout's layout; on another host set the TT_<CONTEXT> env vars (e.g. TT_PTV3SRC) or edit the paths.
$env:DOCKER_BUILDKIT = '1'
Push-Location $PSScriptRoot\..

docker buildx build -f docker/ptv3.Dockerfile -t trainer-local-ptv3 --build-context ptv3src='C:/Users/OrionHoch/Desktop/testSem/PointTransformerV3' --load .
docker buildx build -f docker/ptv3_hag.Dockerfile -t trainer-local-ptv3_hag --build-context ptv3src='C:/Users/OrionHoch/Desktop/testSem/PointTransformerV3' --load .
docker buildx build -f docker/randlanet.Dockerfile -t trainer-local-randlanet --build-context randlanetsrc='C:/Users/OrionHoch/Desktop/testSem/RandLA-Net-pytorch' --load .
docker buildx build -f docker/randlanet_hag.Dockerfile -t trainer-local-randlanet_hag --build-context randlanetsrc='C:/Users/OrionHoch/Desktop/testSem/RandLA-Net-pytorch' --load .
docker buildx build -f docker/kpconvx_cold.Dockerfile -t trainer-local-kpconvx_cold --build-context kpconvxsrc='C:/Users/OrionHoch/Desktop/Modal_H3D/ml-kpconvx/Standalone/KPConvX' --load .
docker buildx build -f docker/kpconvx_cold_hag.Dockerfile -t trainer-local-kpconvx_cold_hag --build-context kpconvxsrc='C:/Users/OrionHoch/Desktop/Modal_H3D/ml-kpconvx/Standalone/KPConvX' --load .

Pop-Location
