#!/usr/bin/env bash
# Auto-generated by tools/gen_dockerfiles.py — build the local backend images. Needs Docker Buildx + an NVIDIA GPU host (--build-context and the RUN <<EOT heredocs require buildx). Adjust the --build-context paths if the model repos live elsewhere on this host.
set -euo pipefail
export DOCKER_BUILDKIT=1
cd "$(dirname "$0")/.."

docker buildx build -f docker/ptv3.Dockerfile -t trainer-local-ptv3 --build-context ptv3src='C:/Users/OrionHoch/Desktop/testSem/PointTransformerV3' --load .
docker buildx build -f docker/ptv3_hag.Dockerfile -t trainer-local-ptv3_hag --build-context ptv3src='C:/Users/OrionHoch/Desktop/testSem/PointTransformerV3' --load .
docker buildx build -f docker/randlanet.Dockerfile -t trainer-local-randlanet --build-context randlanetsrc='C:/Users/OrionHoch/Desktop/testSem/RandLA-Net-pytorch' --load .
docker buildx build -f docker/randlanet_hag.Dockerfile -t trainer-local-randlanet_hag --build-context randlanetsrc='C:/Users/OrionHoch/Desktop/testSem/RandLA-Net-pytorch' --load .
docker buildx build -f docker/kpconvx_cold.Dockerfile -t trainer-local-kpconvx_cold --build-context kpconvxsrc='C:/Users/OrionHoch/Desktop/Modal_H3D/ml-kpconvx/Standalone/KPConvX' --load .
docker buildx build -f docker/kpconvx_cold_hag.Dockerfile -t trainer-local-kpconvx_cold_hag --build-context kpconvxsrc='C:/Users/OrionHoch/Desktop/Modal_H3D/ml-kpconvx/Standalone/KPConvX' --load .
