#!/usr/bin/env bash
# Auto-generated by tools/gen_dockerfiles.py — build the local backend images. Needs Docker Buildx (the RUN <<EOT heredocs require it). Model sources are pinned upstream git clones — buildable on any machine, no local model checkouts needed.
set -euo pipefail
export DOCKER_BUILDKIT=1
cd "$(dirname "$0")/.."

docker buildx build -f docker/ptv3.Dockerfile -t trainer-local-ptv3  --load .
docker buildx build -f docker/ptv3_hag.Dockerfile -t trainer-local-ptv3_hag  --load .
docker buildx build -f docker/randlanet.Dockerfile -t trainer-local-randlanet  --load .
docker buildx build -f docker/randlanet_hag.Dockerfile -t trainer-local-randlanet_hag  --load .
docker buildx build -f docker/kpconvx_cold.Dockerfile -t trainer-local-kpconvx_cold  --load .
docker buildx build -f docker/kpconvx_cold_hag.Dockerfile -t trainer-local-kpconvx_cold_hag  --load .
