"""Emit one Dockerfile per backbone, straight from each script's modal.Image.

The six modal_train_*.py scripts already describe their full environment as a
`modal.Image` builder chain (apt/pip/copy/run/env). We import each under the
offline `_modal_shim` (no Modal account, no torch needed — see _modal_shim.py),
read the recorded recipe, and translate it to an equivalent Dockerfile for a
local NVIDIA+Docker host. So the Dockerfiles never drift from the Modal recipe:
re-run this after editing a script.

    python tools/gen_dockerfiles.py            # writes docker/<key>.Dockerfile + build_all.ps1

The trainer code itself (local_train_*.py) is NOT baked in — it's bind-mounted at
/workspace when you `docker run` (see trainer_gui/local_cli.py), so editing a
script needs no rebuild. Only the heavy deps + the model repo (add_local_dir)
live in the image. (The modal shells DO bake their local_train_*.py via
add_local_file, but this generator skips that copy for the local images.)
"""

from __future__ import annotations

import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# scripts live under scripts/{modal,helper} — put both on the path so the bare
# `modal_train_*` stems and `_modal_shim` import as before.
sys.path.insert(0, REPO)
sys.path.insert(0, os.path.join(REPO, "scripts", "modal"))
sys.path.insert(0, os.path.join(REPO, "scripts", "helper"))

import _modal_shim  # noqa: E402

# backbone key -> script filename (kept in sync with trainer_gui/backbones.py).
SCRIPTS = {
    "ptv3": "modal_train_ptv3.py",
    "ptv3_hag": "modal_train_ptv3_hag.py",
    "randlanet": "modal_train_randlanet.py",
    "randlanet_hag": "modal_train_randlanet_hag.py",
    "kpconvx_cold": "modal_train_kpconvx_cold.py",
    "kpconvx_cold_hag": "modal_train_kpconvx_cold_hag.py",
    "kpconv": "modal_train_kpconv.py",
    "kpconv_hag": "modal_train_kpconv_hag.py",
}

# pip wheel channel -> CUDA toolkit tag for the `nvidia/cuda:<ver>-devel` base.
# devel (not runtime) so nvcc is present for pykeops JIT + any source builds;
# torch wheels bundle their own cuDNN, so the plain devel image is enough.
_CUDA = [("cu124", "12.4.0"), ("cu126", "12.6.0"), ("cu121", "12.1.0"),
         ("cu118", "11.8.0"), ("cu117", "11.7.0")]


def _recipe(script_stem):
    _modal_shim.install()
    for m in list(sys.modules):
        if m.startswith("modal_train_"):
            sys.modules.pop(m, None)
    import importlib
    mod = importlib.import_module(script_stem)
    img = _modal_shim.App.last.image or getattr(mod, "image", None)
    if img is None or not getattr(img, "steps", None):
        raise RuntimeError(f"{script_stem}: no recorded Image recipe")
    return img


def _cuda_ver(steps):
    for kind, p in steps:
        if kind == "pip":
            for blob in (p.get("index_url"), p.get("find_links")):
                if blob:
                    for tag, ver in _CUDA:
                        if tag in blob:
                            return ver
    return None


def _ctx_name(dst):
    return os.path.basename(dst.rstrip("/")).replace("-", "").replace("_", "") + "src"


def _q(pkg):
    # version specs like `numpy<2.0` / `pandas<3` contain shell redirects in the
    # Dockerfile's shell-form RUN — quote anything with a metachar.
    return f"'{pkg}'" if any(c in pkg for c in "<>| \t") else pkg


def _pip_line(p):
    parts = ["RUN python -m pip install --no-cache-dir"]
    if p.get("pre"):
        parts.append("--pre")
    parts.extend(_q(x) for x in p["pkgs"])
    if p.get("index_url"):
        parts.append(f"--index-url {p['index_url']}")
    if p.get("extra_index_url"):
        parts.append(f"--extra-index-url {p['extra_index_url']}")
    if p.get("find_links"):
        parts.append(f"--find-links {p['find_links']}")
    return " ".join(parts)


def build_dockerfile(key, script):
    img = _recipe(os.path.splitext(script)[0])
    steps = img.steps
    cuda = _cuda_ver(steps)
    base = (f"nvidia/cuda:{cuda}-devel-ubuntu22.04" if cuda
            else "python:3.10-slim  # NOTE: no CUDA channel detected — review")

    apt_pkgs = []
    for kind, p in steps:
        if kind == "apt":
            apt_pkgs += p
    # ubuntu 22.04 already ships python 3.10. python3-dev gives Python.h — the
    # KPConv/RandLA C++ extensions #include it at build_ext time and fail without
    # it (Modal's debian_slim bundled the headers; the CUDA base doesn't). The
    # symlink below gives us `python` (python-is-python3 lives in `universe`).
    boot = ["python3", "python3-pip", "python3-dev"] + apt_pkgs

    contexts = {}   # ctx name -> host src
    out = [
        # Pin a heredoc/build-context-capable frontend so `RUN <<EOT` and named
        # build contexts parse on any engine (must be the literal first line).
        "# syntax=docker/dockerfile:1",
        f"# Auto-generated by tools/gen_dockerfiles.py from {script}'s modal.Image recipe.",
        f"# DO NOT edit by hand — re-run the generator after changing the script.",
        f"# Build from the repo root with Buildx (see docker/build_all.ps1):",
        f"#   docker buildx build -f docker/{key}.Dockerfile -t trainer-local-{key} <ctx-flags> --load .",
        f"FROM {base}",
        "ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1",
        "RUN apt-get update && apt-get install -y --no-install-recommends \\",
        "      " + " ".join(boot) + " \\",
        "    && rm -rf /var/lib/apt/lists/*",
        "RUN ln -sf /usr/bin/python3 /usr/bin/python",
        "RUN python -m pip install --no-cache-dir --upgrade pip",
    ]

    for kind, p in steps:
        if kind == "apt":
            continue  # merged into the bootstrap apt above
        if kind == "pip":
            out.append(_pip_line(p))
        elif kind == "pip_req":
            out.append(f"COPY {p} /tmp/requirements.txt")
            out.append("RUN python -m pip install --no-cache-dir -r /tmp/requirements.txt")
        elif kind == "env":
            out.append("ENV " + " ".join(f"{k}={v}" for k, v in p.items()))
        elif kind in ("copy_dir", "copy_file"):
            # The modal shell bakes local_train_*.py and train_common.py into its
            # image, but locally those repo-root files are already bind-mounted at
            # /workspace (run_script runs from there) — so skip baking them; only
            # the model repo (add_local_dir) is baked. ponytail: basename match,
            # the repo-root trainer files are the only copy steps we ever skip.
            base = os.path.basename(p["src"])
            if base.startswith("local_train_") or base in ("train_common.py", "density.py"):
                continue
            ctx = _ctx_name(p["dst"])
            contexts[ctx] = p["src"]
            out.append(f"COPY --from={ctx} . {p['dst']}")
        elif kind == "run":
            for cmd in p:
                if "\n" in cmd:                       # multi-line (heredoc) -> RUN <<EOT
                    out.append("RUN <<'TT_EOT'")
                    out.append(cmd)
                    out.append("TT_EOT")
                else:
                    out.append(f"RUN {cmd}")
        elif kind == "workdir":
            out.append(f"WORKDIR {p}")

    out.append("WORKDIR /workspace")
    return "\n".join(out) + "\n", contexts


def main():
    docker_dir = os.path.join(REPO, "docker")
    os.makedirs(docker_dir, exist_ok=True)
    all_ctx = {}
    for key, script in SCRIPTS.items():
        text, contexts = build_dockerfile(key, script)
        path = os.path.join(docker_dir, f"{key}.Dockerfile")
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        all_ctx[key] = contexts
        print(f"wrote docker/{key}.Dockerfile  (cuda base, {len(contexts)} build-context(s))")

    # Build scripts (PowerShell + bash) with the exact --build-context flags per
    # image. The build host is wherever Docker+GPU lives (often Linux); on a non-
    # Windows host adjust the --build-context source paths to where the model repos
    # are checked out.
    any_ctx = any(all_ctx.values())
    note = ("Auto-generated by tools/gen_dockerfiles.py — build the local backend images. "
            "Needs Docker Buildx (the RUN <<EOT heredocs require it). "
            + ("Paths default to this checkout's layout; on another host set the "
               "TT_<CONTEXT> env vars (e.g. TT_PTV3SRC) or edit the paths."
               if any_ctx else
               "Model sources are pinned upstream git clones — buildable on any "
               "machine, no local model checkouts needed."))
    # build_all.sh makes each model-repo path overridable via a TT_<CONTEXT> env var
    # (the build host is often a different, non-Windows machine); build_all.ps1 keeps
    # the literal default (it runs on the box these were generated on). L6.
    builds_sh, builds_ps1 = [], []
    for key, contexts in all_ctx.items():
        base = f"docker buildx build -f docker/{key}.Dockerfile -t trainer-local-{key} "
        ps_flags = " ".join(f"--build-context {c}='{src}'" for c, src in contexts.items())
        sh_flags = " ".join(f'--build-context {c}="${{{"TT_" + c.upper()}:-{src}}}"'
                            for c, src in contexts.items())
        builds_ps1.append(base + ps_flags + " --load .")
        builds_sh.append(base + sh_flags + " --load .")

    ps1 = ["# " + note, "$env:DOCKER_BUILDKIT = '1'", "Push-Location $PSScriptRoot\\..", ""]
    ps1 += builds_ps1 + ["", "Pop-Location"]
    with open(os.path.join(docker_dir, "build_all.ps1"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(ps1) + "\n")

    sh = ["#!/usr/bin/env bash", "# " + note, "set -euo pipefail",
          "export DOCKER_BUILDKIT=1", 'cd "$(dirname "$0")/.."', ""]
    sh += builds_sh
    with open(os.path.join(docker_dir, "build_all.sh"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(sh) + "\n")

    # Registry distribution: push the built images once, pull them on machines
    # that won't build (they need no model repos — the code is baked into each
    # image). TT_REGISTRY is the single knob, shared with the GUI's
    # local_config['registry']; it defaults to our gcsgeospatial GHCR org.
    default_reg = "ghcr.io/gcsgeospatial"
    def _write(fname, lines, crlf=False):
        nl = "\r\n" if crlf else "\n"
        with open(os.path.join(docker_dir, fname), "w", encoding="utf-8", newline=nl) as f:
            f.write("\n".join(lines) + "\n")

    sh_keys = " ".join(SCRIPTS)
    ps_keys = ",".join(f'"{k}"' for k in SCRIPTS)
    push_note = ("Tag + push the locally-built trainer-local-* images to a registry so other "
                 "machines can pull them (no model repos needed — the code is baked in).")
    pull_note = "Pull the trainer-local-* images on a machine that won't build them."
    # Default TT_REGISTRY to our org if unset (`:=` / -not) — `docker login` first
    # if the packages are private.
    sh_guard = f': "${{TT_REGISTRY:={default_reg}}}"'
    ps_guard = f'if (-not $env:TT_REGISTRY) {{ $env:TT_REGISTRY = "{default_reg}" }}'

    _write("push_all.sh", [
        "#!/usr/bin/env bash", "# " + push_note,
        f"# Usage:  bash docker/push_all.sh   (TT_REGISTRY={default_reg} by default; docker login first)",
        "set -euo pipefail", sh_guard, f"for key in {sh_keys}; do",
        '  docker tag "trainer-local-$key" "$TT_REGISTRY/trainer-local-$key:latest"',
        '  docker push "$TT_REGISTRY/trainer-local-$key:latest"', "done",
        'echo "pushed to $TT_REGISTRY — set TT_REGISTRY (or local_config[\'registry\']) there too."'])
    _write("pull_all.sh", [
        "#!/usr/bin/env bash", "# " + pull_note,
        f"# Usage:  bash docker/pull_all.sh   (TT_REGISTRY={default_reg} by default)",
        "set -euo pipefail", sh_guard, f"for key in {sh_keys}; do",
        '  docker pull "$TT_REGISTRY/trainer-local-$key:latest"', "done"])
    _write("push_all.ps1", [
        "# " + push_note, ps_guard, f"foreach ($key in @({ps_keys})) {{",
        '  docker tag "trainer-local-$key" "$env:TT_REGISTRY/trainer-local-$key:latest"',
        '  docker push "$env:TT_REGISTRY/trainer-local-$key:latest"', "}"], crlf=True)
    _write("pull_all.ps1", [
        "# " + pull_note, ps_guard, f"foreach ($key in @({ps_keys})) {{",
        '  docker pull "$env:TT_REGISTRY/trainer-local-$key:latest"', "}"], crlf=True)

    print("wrote docker/build_all + push_all + pull_all (.ps1 + .sh)")


if __name__ == "__main__":
    main()
